on:
  delete:

name: Cleanup AWS

jobs:
  delete:
    name: Delete old stack
    runs-on: ubuntu-20.04
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Define slug variables
        uses: rlespinasse/github-slug-action@v4

      - name: Set STACK_NAME
        env:
          STACK_NAME_BASE: ${{ env.GITHUB_REPOSITORY_NAME_PART }}
        run: |
          echo "STACK_NAME=${STACK_NAME_BASE}-${{ env.GITHUB_EVENT_REF_SLUG }}" >> $GITHUB_ENV

      - name: cleanup AWS
        run: |
          echo using STACK_NAME ${{ env.STACK_NAME }}
          aws cloudformation delete-stack --stack-name="${{ env.STACK_NAME }}"
