on:
  push:
    paths-ignore:
      - 'cfn/aws-base*.yml'
      - 'docs/*'
    branches-ignore:
      - 'wip-**'
  workflow_dispatch:

name: Deploy to AWS Lambda

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Make
        id: package
        run: |
          make

      - name: Define slug variables
        uses: rlespinasse/github-slug-action@v4

      - name: Set STACK_NAME
        env:
          STACK_NAME_BASE: ${{ env.GITHUB_REPOSITORY_NAME_PART }}
        run: |
          echo "STACK_NAME=${STACK_NAME_BASE}-${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_ENV

      - name: Set API Base Name
        run: |
          if [ "${{ env.GITHUB_REF_SLUG }}" == "master" ]
          then
            echo "API_BASENAME=api" >> $GITHUB_ENV
          else
            echo "API_BASENAME=${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_ENV
          fi

      - name: Deploy
        id: deploy
        env:
          S3_BUCKET: nc-projects-infrabucket
        working-directory: ./cfn
        run: |
          echo using STACK_NAME ${{ env.STACK_NAME }}
          aws cloudformation package --template aws-resources.yml --s3-bucket $S3_BUCKET --s3-prefix ${{ env.GITHUB_REPOSITORY_NAME_PART }} --output-template template-export.yml
          aws cloudformation deploy  --template-file=template-export.yml --stack-name="${{ env.STACK_NAME }}" --capabilities=CAPABILITY_NAMED_IAM --parameter-overrides ParamDomainName=${{ secrets.AWS_API_DOMAINNAME}} ParamBaseName=${{ env.API_BASENAME }}
          export ENDPOINT=$(aws cloudformation describe-stacks --stack-name="${{ env.STACK_NAME }}" | jq -r '.Stacks | .[0] | .Outputs[] | select(.OutputKey=="LambdaEndpoint") | .OutputValue')
          echo "ENDPOINT=${ENDPOINT}" >> $GITHUB_ENV
      - name: Verify
        run: |
          echo Using endpoint ${{ env.ENDPOINT }}
